enum ActionTypeKeys {
    LOAD_DATASET="LOAD_DATASET",
    LOAD_DATASET_INPROGRESS="LOAD_DATASET_INPROGRESS",
    LOAD_DATASET_ERROR="LOAD_DATASET_ERROR",
    LOAD_DATASET_SUCCESS="LOAD_DATASET_SUCCESS",
    LOAD_LAR_DATA="LOAD_LAR_DATA",
    LOAD_LAR_DATA_INPROGRESS="LOAD_LAR_DATA_INPROGRESS",
    LOAD_LAR_DATA_ERROR="LOAD_LAR_DATA_ERROR",
    LOAD_LAR_DATA_SUCCESS="LOAD_LAR_DATA_SUCCESS"
}

export default ActionTypeKeys;