enum ActionTypeKeys {
    LOAD_DATASET="LOAD_DATASET",
    LOAD_DATASET_INPROGRESS="LOAD_DATASET_INPROGRESS",
    LOAD_DATASET_ERROR="LOAD_DATASET_ERROR",
    LOAD_DATASET_SUCCESS="LOAD_DATASET_SUCCESS"
}

export default ActionTypeKeys;